//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace frmSplash.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("frmSplash.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _02b2e53b67e063e59ee1c8235283aa28 {
            get {
                object obj = ResourceManager.GetObject("02b2e53b67e063e59ee1c8235283aa28", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9975fac6938d6d19c33105e44655a3c8_design_de_logotipo_do_restaurante_cheff {
            get {
                object obj = ResourceManager.GetObject("9975fac6938d6d19c33105e44655a3c8-design-de-logotipo-do-restaurante-cheff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9975fac6938d6d19c33105e44655a3c8_design_de_logotipo_do_restaurante_cheff1 {
            get {
                object obj = ResourceManager.GetObject("9975fac6938d6d19c33105e44655a3c8-design-de-logotipo-do-restaurante-cheff1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ae9a889bdd2a489862b6314399c84b45 {
            get {
                object obj = ResourceManager.GetObject("ae9a889bdd2a489862b6314399c84b45", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Como_usar_delivery_logo_para_meu_restaurante_SAIPOS_Sistema_Para_restaurante_10 {
            get {
                object obj = ResourceManager.GetObject("Como-usar-delivery-logo-para-meu-restaurante-SAIPOS-Sistema-Para-restaurante-10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Como_usar_delivery_logo_para_meu_restaurante_SAIPOS_Sistema_Para_restaurante_101 {
            get {
                object obj = ResourceManager.GetObject("Como-usar-delivery-logo-para-meu-restaurante-SAIPOS-Sistema-Para-restaurante-101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Como_usar_delivery_logo_para_meu_restaurante_SAIPOS_Sistema_Para_restaurante_102 {
            get {
                object obj = ResourceManager.GetObject("Como-usar-delivery-logo-para-meu-restaurante-SAIPOS-Sistema-Para-restaurante-102", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Como_usar_delivery_logo_para_meu_restaurante_SAIPOS_Sistema_Para_restaurante_103 {
            get {
                object obj = ResourceManager.GetObject("Como-usar-delivery-logo-para-meu-restaurante-SAIPOS-Sistema-Para-restaurante-103", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_169536646_stock_photo_red_wallpaper_texture {
            get {
                object obj = ResourceManager.GetObject("depositphotos_169536646-stock-photo-red-wallpaper-texture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_169536646_stock_photo_red_wallpaper_texture1 {
            get {
                object obj = ResourceManager.GetObject("depositphotos_169536646-stock-photo-red-wallpaper-texture1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap depositphotos_169536646_stock_photo_red_wallpaper_texture2 {
            get {
                object obj = ResourceManager.GetObject("depositphotos_169536646-stock-photo-red-wallpaper-texture2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download__1_ {
            get {
                object obj = ResourceManager.GetObject("download (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_position_map {
            get {
                object obj = ResourceManager.GetObject("icon-position-map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_639523652_170667a {
            get {
                object obj = ResourceManager.GetObject("istockphoto-639523652-170667a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_639523652_170667a1 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-639523652-170667a1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_639523652_170667a2 {
            get {
                object obj = ResourceManager.GetObject("istockphoto-639523652-170667a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logotipo_do_restaurante_retro_23_2148474404 {
            get {
                object obj = ResourceManager.GetObject("logotipo-do-restaurante-retro_23-2148474404", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logotipo_personalizada_restaurante_arte_digital_restaurante {
            get {
                object obj = ResourceManager.GetObject("logotipo-personalizada-restaurante-arte-digital-restaurante", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logotipo_personalizada_restaurante_logotipo_restaurante {
            get {
                object obj = ResourceManager.GetObject("logotipo-personalizada-restaurante-logotipo-restaurante", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_graphics_restaurant_logo_restaurant {
            get {
                object obj = ResourceManager.GetObject("png-clipart-graphics-restaurant-logo-restaurant", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap png_clipart_graphics_restaurant_logo_restaurant1 {
            get {
                object obj = ResourceManager.GetObject("png-clipart-graphics-restaurant-logo-restaurant1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_restaurant_food_menu_background_image_190820 {
            get {
                object obj = ResourceManager.GetObject("pngtree-restaurant-food-menu-background-image_190820", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_restaurant_food_menu_background_image_190820__1_ {
            get {
                object obj = ResourceManager.GetObject("pngtree-restaurant-food-menu-background-image_190820 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_restaurant_food_menu_background_image_1908201 {
            get {
                object obj = ResourceManager.GetObject("pngtree-restaurant-food-menu-background-image_1908201", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_restaurant_food_menu_background_image_1908202 {
            get {
                object obj = ResourceManager.GetObject("pngtree-restaurant-food-menu-background-image_1908202", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_1636485138850 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_1636485138850", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_16364851388501 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_16364851388501", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_1636485475400__1_ {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_1636485475400 (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_1636485576832 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_1636485576832", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_1636485734101 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_1636485734101", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_16364857341011 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_16364857341011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_16364857341012 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_16364857341012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_16364857341013 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_16364857341013", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_16364857341014 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_16364857341014", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_1636485917761 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_1636485917761", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SGN_11_09_2021_16364859177611 {
            get {
                object obj = ResourceManager.GetObject("SGN_11_09_2021_16364859177611", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
